### PR TITLE
IDEX-3882. Rename dev-machine to ws-machine

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Rename dev-machine to ws-machine

### CODE REVIEW

**Comment by benoitf** [comment]
sorry, didn't see PR
+1

**Comment by benoitf** [comment]
ok, please use "merge with fast forward mode" next time
thanks

**Comment by RomanNikitenko** [comment]
ok, sorry...

**Comment by benoitf** [comment]
np, I didn't say it so my fault

**Pull request merged**
