### PR TITLE
UD-946 improve styles for the "What should http://localhost:8080 Load"

### PR DESCRIPTION
**Pull request by akurinnoy**
screenshot welcome back

### CODE REVIEW

**Comment by benoitf** [comment]
the URL is not displayed anymore and is replaced by &quot;/&quot;  everytime ? It's expected ?

**Comment by akurinnoy** [comment]
Stevan have just changed his mind, I'll put URL back

**Comment by akurinnoy** [comment]
@benoitf WDYT

**Comment by akurinnoy** [comment]
@benoitf 
screenshot welcome back 2

**Comment by benoitf** [comment]
ok for me, thx for the snapshot

**Pull request merged**
