### PR TITLE
CDEC-485: add create user form

### PR DESCRIPTION
**Pull request by olexii4**
@benoitf  WDYT?

### CODE REVIEW

**Comment by benoitf** [comment]
OK for me

**Comment by ashumilova** [comment]
+1

**Comment by benoitf** [comment]
Check header copyright date it seems to be invalid ( mvn clean install is working ? )

**Comment by olexii4** [comment]
mvn clean install was working(I guess HTML license wasn't checked)

**Comment by olexii4** [comment]
Fixed

**Comment by benoitf** [comment]
@olexii4 ok so I will look if .styl or html can be checked as well as part of license checker

**Pull request merged**
