### PR TITLE
UD-947: add filters for the library of stacks

### PR DESCRIPTION
**Pull request by akurinnoy**
screenshot

### CODE REVIEW

**Comment by akurinnoy** [comment]
@ashumilova @benoitf WDYT

**Comment by benoitf** [comment]
image
I notice I have some empty spaces now around the stacks

**Comment by akurinnoy** [comment]
screenshot_1
screenshot_3

**Comment by benoitf** [comment]
image
text is not vertically centered

**Comment by akurinnoy** [comment]
screenshot_4

**Comment by benoitf** [comment]
for the code it's ok for me, about UI need @slemeur +1 :-)

**Comment by ashumilova** [comment]
need to update PR with the latest changes

**Comment by ashumilova** [comment]
Few UI notes:
1. change black focused tag state
2. message "Use tab or   to navigate. Return to add." bind more to suggestions. when there are no suggestion - no need in message. And also layout is moving up and down when suggestions appear/hide
suggestion_message

**Comment by benoitf** [comment]
I'm merging so I will be able to apply rename in repository this week end

**Pull request merged**
