### PR TITLE
IDEX-400 Adopt to changes in user API

### PR DESCRIPTION
**Pull request by skabashnyuk**
Linked PR https://github.com/codenvy/che-core/pull/596

### CODE REVIEW

**Comment by skabashnyuk** [comment]
@ashumilova  please review

**Comment by benoitf** [comment]
if it's not anymore a find by email method
method needs to be renamed
findByEmail --> findByAlias
rename parameter email into alias as well

and attribute userEmailMap should be renamed as well to userAliasMap

**Comment by benoitf** [comment]
hum this shouldn't have been merged with the fixup commit

**Comment by skabashnyuk** [comment]
yep. Me and Ann  decided to leave her commit as is.

**Pull request merged**
