### PR TITLE
UD-881: add slider for RAM allocation

### PR DESCRIPTION
**Pull request by akurinnoy**

### CODE REVIEW

**Comment by benoitf** [comment]
Firs comment : There is no signed CLA for this email at https://projects.eclipse.org/user/cla/validate
before accepting CLA needs to be signed

**Comment by benoitf** [comment]
About the code, as the ram selector will be present in several tabs, it should be done as a new directive
Else we will duplicate the code in each tab

**Comment by akurinnoy** [comment]
@ashumilova WDYT?

**Comment by benoitf** [comment]
It would be nice to have a <workspace-ram-slider ng-model="..." (or cdvy-value="")> directive
As workspace RAM slider will be used as several places, it will be included in many screens, and then there is a lot of copy/paste for the same minimal value, max values, increment, title, etc
by having as well a directive only for the workspace ram, it will be better

to sum up : two directives : generic one slider and a workspace slider

**Pull request merged**
