### PR TITLE
UD-994: add ability to start a workspace from UD

### PR DESCRIPTION
**Pull request by akurinnoy**
screenshot stopped
screenshot starting
screenshot running

### CODE REVIEW

**Comment by akurinnoy** [comment]
@benoitf @ashumilova WDYT

**Comment by ashumilova** [comment]
can you please make run/stop button same size as rename (from demo notes). Other : +1

**Comment by akurinnoy** [comment]
ok

**Comment by akurinnoy** [comment]
screenshot stopped
screenshot starting
screenshot running

**Comment by benoitf** [comment]
+1

**Pull request merged**
