### PR TITLE
UD-884 Restyle create project template section

### PR DESCRIPTION
**Pull request by mkuznyetsov**

### CODE REVIEW

**Comment by benoitf** [comment]
Selecting spring project in the list of template is not cloning the project (project is created but without data)
may it's because we're not using 'import' but create there
https://github.com/codenvy/che-dashboard/blob/master/src/app/projects/create-project/create-project.controller.js#L403-L419

**Comment by mkuznyetsov** [comment]
I guess, it is for another issue, this one was mainly about styling

**Comment by benoitf** [comment]
ok

**Comment by benoitf** [comment]
so let's merge your PR

**Pull request merged**
