### PR TITLE
UD-940 improve the slider's for ram

### PR DESCRIPTION
**Pull request by akurinnoy**

### CODE REVIEW

**Comment by akurinnoy** [comment]
@ashumilova what do you think?

**Comment by benoitf** [comment]
image
ok for me

**Comment by benoitf** [comment]
it seems it has been committed but without using the merge of this PR ?

**Comment by akurinnoy** [comment]
merged as 48a7157edd2df8204927bd0b6e2b1f08da593c62

**Comment by benoitf** [comment]
it's not a git 'merged', it's like a cherry-pick

**Pull request closed without merging**
