### PR TITLE
UD-925 in project-creation loading flow / workspace-creation loading …

### PR DESCRIPTION
**Pull request by akurinnoy**
…flow,

 change the button "open in ide" button's style

### CODE REVIEW

**Comment by akurinnoy** [comment]
@ashumilova @benoitf WDYT

**Comment by benoitf** [comment]
pls remove the two occurences of "fa"
cdvy-button-icon="fa fa fa-chevron-circle-right"

(well I think we have the error elsewhere ;-)

then +1 for me

**Comment by ashumilova** [comment]
+1

**Comment by benoitf** [comment]
I see too late that closing element of primary button is not the same
I will fix in another commit

opening is <cdvy-button-primary>  while closing is </cdvy-button-default>

**Pull request merged**
