### PR TITLE
UD-999: improve the slider's for ram

### PR DESCRIPTION
**Pull request by akurinnoy**

### CODE REVIEW

**Comment by akurinnoy** [comment]
@benoitf @ashumilova WDYT

**Comment by benoitf** [comment]
- need initial value in placeholder with up/down
- need sync between the up/down widget and slider widget

**Comment by akurinnoy** [comment]
screenshot ram slider

**Comment by benoitf** [comment]
image
I still don't show initial/selected value in up/down selector when loading page

**Comment by ashumilova** [comment]
checked on my side, it's ok - i have init value set to 1.

**Comment by akurinnoy** [comment]
@ashumilova @benoitf WDYT

**Comment by benoitf** [comment]
+1 (squashing all intermediate commits before merging into master branch)

**Comment by benoitf** [comment]
I forgot : this commit should have its own commit and own issue "fix behavior of STOP button in workspace details"

**Comment by ashumilova** [comment]
+1

**Comment by ashumilova** [comment]
UD-1030 - will come with next PR

**Comment by benoitf** [comment]
perfect

**Pull request merged**
